//
//  Affirmations.swift
//  WhiteRabbits
//
//  One quiet line a day. Secular, light, no homework.
//  Day of the year picks the line, so opening the app is always a small gift.
//

import Foundation

enum Affirmations {
    static func line(for date: Date = Date()) -> String {
        let day = Calendar.current.ordinality(of: .day, in: .year, for: date) ?? 1
        return all[(day - 1) % all.count]
    }

    /// 365 lines, January to December. A leap day shares 1 March, on purpose.
    static let all: [String] = [
        // January
        "A quiet white beginning. The year is still unwritten.",
        "You woke up. That is already a kind of luck.",
        "Nothing to prove this morning. Only a little light to stand in.",
        "Someone, somewhere, is glad you are here.",
        "Go gently. The day will meet you halfway.",
        "You do not have to earn a soft start.",
        "A small kindness to yourself counts as a plan.",
        "The year will wait while you drink your tea.",
        "You are allowed to begin again at any hour.",
        "Luck likes people who keep showing up.",
        "Put one kind thought in your pocket and go.",
        "The world is loud. You can still be quiet inside it.",
        "Today can be ordinary and still be good.",
        "You have survived every hard day so far.",
        "A fresh page does not ask you to fill it.",
        "Rest is not a prize. It is part of the work.",
        "You are not behind. You are in a life.",
        "Let the morning be simple. That is enough.",
        "Even a tiny bit of hope will do.",
        "The light comes back. It always does.",
        "You can take up a little space today.",
        "Be on your own side, just for this hour.",
        "A slow day is still a day that counts.",
        "You do not need a reason to feel glad.",
        "Keep the good thought. Leave the rest.",
        "There is room for you in this morning.",
        "You are doing better than the worried part thinks.",
        "Warmth is a kind of luck. Stand in it.",
        "No scoreboard. Just a life, unfolding.",
        "The next right thing can be very small.",
        "You are allowed to want an easy day.",
        // February
        "A small tenderness, kept close.",
        "Breathe. The hour is not in a hurry.",
        "A past version of you would be proud you made it here.",
        "Let today be a kindness, not a test.",
        "You can put the heavy thing down for a minute.",
        "Good things also happen on grey mornings.",
        "You belong to this day as much as anyone.",
        "A little luck is already on its way.",
        "Stay with what is true and kind.",
        "You do not have to be impressive to be loved.",
        "The day is wide. Walk into it softly.",
        "Your company is a gift, including to yourself.",
        "It is all right to hope for a gentle afternoon.",
        "You have time. Not all of it, but enough for this.",
        "A quiet win still counts as a win.",
        "Let your shoulders drop. You are safe enough for now.",
        "The best plans sometimes look like rest.",
        "You can be new without throwing the old away.",
        "Someone is rooting for you. Today it can be you.",
        "Hold something small and lovely in your mind.",
        "The month will keep its shape. You only have to live it.",
        "You are not too much, and you are not too late.",
        "A soft word to yourself will travel far.",
        "This hour does not need a masterpiece.",
        "Come back to the body. It has been waiting.",
        "You can love a day that is only all right.",
        "Leave a little room for surprise.",
        "The hard season is not the whole story.",
        // March
        "Light and dark in equal measure. Begin in balance.",
        "March will find its light. So will you.",
        "What grows slowly still grows.",
        "You can be tender and still be strong enough.",
        "The rain is not against you.",
        "A fresh air kind of courage will do.",
        "You have not missed your life. You are in it.",
        "Let one true thing be enough for now.",
        "The window is open somewhere. Go stand near it.",
        "You do not owe the day a performance.",
        "Keep the promise that is kindest.",
        "A little green is coming, even if you cannot see it yet.",
        "You are allowed to ask for help without apology.",
        "Walk as if the pavement likes you.",
        "Today, choose the gentler story about yourself.",
        "Luck is not loud. It often arrives as a pause.",
        "You can start in the middle. Most people do.",
        "Be easy to be with, starting with you.",
        "A good night of sleep is a kind of wealth.",
        "The season is turning. You can turn with it.",
        "You are not required to bloom on command.",
        "Hold the line that says you are all right.",
        "Even a cloudy day has a colour.",
        "You can put flowers in a jam jar and call it a ceremony.",
        "The work can wait five minutes. You cannot always.",
        "A friend in your corner is a kind of weather.",
        "You have a right to a peaceful breakfast.",
        "Let the small joy be the whole joy.",
        "You are not a project. You are a person.",
        "Whatever happens, you can come home to yourself.",
        "A kind afternoon is a perfectly good ambition.",
        // April
        "What falls, feeds. Let the month arrive softly.",
        "Keep your luck close and your humour closer.",
        "The body knows how to rest if you let it.",
        "You are already someone’s good news.",
        "A clean sheet, a clear mug, a new hour.",
        "Go where the light is, even if it is only a lamp.",
        "You can be unfinished and still be welcome.",
        "The day will not collapse if you are slow.",
        "Write a kinder headline for this morning.",
        "You have been brave in ways nobody saw.",
        "Let April be weather, not a verdict.",
        "You are allowed to outgrow a thought.",
        "Keep a little wonder. It costs nothing.",
        "The world is still capable of being lovely.",
        "You can take the long way round.",
        "A warm drink is a tiny roof over the day.",
        "Do not rush the good part.",
        "You are more than the list in your head.",
        "If it is heavy, put it down in another room for now.",
        "A quiet life is not a small life.",
        "You can be proud of an ordinary Tuesday.",
        "Luck likes a person who is kind at the counter.",
        "Leave the curtains open a little longer.",
        "You do not need a grand plan to be hopeful.",
        "The next season is already practising.",
        "Be the person who texts back with warmth.",
        "You can forgive the morning for starting early.",
        "A little ritual is a handrail. Use it.",
        "You are allowed to want less, and also more.",
        "Stay for the bit that feels like home.",
        // May
        "A brief, perfect opening. You can have one too.",
        "The sky does this every day, and still it is new.",
        "You have not used up your chance to be happy.",
        "Let somebody be glad to see you, including you.",
        "A slow walk counts as looking after yourself.",
        "You can put the phone down and still be loved.",
        "There is luck in a door that opens easily.",
        "Keep the part of you that notices blossom.",
        "You do not have to earn the weekend in advance.",
        "A May morning is allowed to be enough.",
        "You can say no and remain a good person.",
        "The light is longer. Spend a little of it on nothing.",
        "You are not late for your own life.",
        "A picnic of one is still a celebration.",
        "Let the window do some of the work.",
        "You can be delighted by small, silly things.",
        "Keep your softness. The world has enough edges.",
        "A good laugh is a kind of reset.",
        "You belong in the warm bit of the day.",
        "Do one thing at the pace of a human.",
        "You are allowed to change the plan because the sun came out.",
        "Hope can be as light as a cotton sleeve.",
        "The garden does not hurry, and it still arrives.",
        "You can take a compliment and keep it.",
        "A clear table is a kind of peace.",
        "Be generous with your own mistakes.",
        "You do not have to be in a good mood to be kind.",
        "Leave a little time that belongs to nobody.",
        "You are allowed to like your own company.",
        "A green day. Go and get a bit of it.",
        "The month is opening. You can open with it.",
        // June
        "The longest light. Stay in it a little longer.",
        "Let June hold the door for you.",
        "You can love a day that asks very little.",
        "A swim, a stretch, a sit. Any of those will do.",
        "You are not required to be useful every minute.",
        "Keep the evening free of a verdict.",
        "Luck sometimes looks like a cancelled plan.",
        "You can be the calm person in the room, including your own.",
        "A ripe peach is a perfectly good philosophy.",
        "Let the heat be an excuse to go slower.",
        "You have a right to shade and water and rest.",
        "The year is only half done. Plenty of room.",
        "You can put your feet up without a speech.",
        "A shared joke is a kind of shelter.",
        "Do not tidy the joy away too quickly.",
        "You are allowed to be a beginner again.",
        "The sea does not ask you to be impressive.",
        "A paper fan, a cold drink, a pause.",
        "You can leave some messages for tomorrow.",
        "Keep the people who make the room easier.",
        "You do not have to finish the book tonight.",
        "Stand still until the good feeling catches up.",
        "You have not wasted a day that held a laugh.",
        "Wear the lucky thing for no reason.",
        "A long evening is a gift. Spend it slowly.",
        "You can say yes to the easy option.",
        "Light on the wall is a kind of company.",
        "You are allowed to be unspectacular and happy.",
        "Keep a window open for the night air.",
        "The month will be kind if you let it.",
        // July
        "Warmth as a kind of luck. Take your share.",
        "A July evening can be the whole holiday.",
        "Let the day be a little bit lazy on purpose.",
        "You are more than your inbox.",
        "The sun will go down. You can too.",
        "A kind word travels further in the heat.",
        "You can love a day that is only weather and water.",
        "A full fridge and a quiet house is a kind of riches.",
        "Keep the charm close. It is only a reminder you are liked.",
        "You can be proud of getting through the week.",
        "The first cool night, when it comes, is a small present.",
        "You are not obliged to make it meaningful.",
        "A walk after supper will sort more than a list.",
        "Let the evening be longer than the worry.",
        "You do not have to gather everything at once.",
        "Ice in a glass is a tiny celebration.",
        "You can take the afternoon off from being impressive.",
        "A shadow to sit in is a luxury. Use it.",
        "Keep your humour when the air is thick.",
        "You are allowed to do less than you planned.",
        "The holiday can be an hour. That still counts.",
        "A late breakfast is a civilised rebellion.",
        "You can keep a secret kindness for yourself.",
        "Salt, sun, sleep. Any order will do.",
        "Let someone else choose the film.",
        "You have a right to a slow Sunday in the middle of the week.",
        "The light is generous. Be generous back, starting with you.",
        "A fan, a book, a doze. Honourable work.",
        "You can leave the house later. The day will wait.",
        "Warm air, cool drink, nothing to solve.",
        "You made it to the long days. Stay for them.",
        // August
        "Golden hour, gathered. Let it land on you.",
        "August does not need you to be busy to be yours.",
        "The year begins to glow, even in ordinary rooms.",
        "You are allowed to miss people and still have a nice day.",
        "A train window is a free film. Watch it.",
        "You can put the lucky thought in your pocket again.",
        "A harvest of small good things is still a harvest.",
        "Keep the late light. It will not stay forever.",
        "You do not have to finish the summer. You can just be in it.",
        "A peach, a pavement, a pause.",
        "Let the evening meal be the event.",
        "You are allowed to feel the year turning and still be glad.",
        "Bare feet on a cool floor is a kind of luck.",
        "You can send the kind text and then put the phone down.",
        "The month is golden. You do not have to polish it.",
        "A quiet street at dusk is a whole holiday.",
        "You have not missed the best bit. It might be tonight.",
        "Keep the window open until the last of the warmth.",
        "You can be tired of heat and still love the light.",
        "A paper bag of something nice. That is a plan.",
        "Let August be easy. It is trying to be.",
        "You are already in the good part of the year.",
        "A long shadow means the day was full enough.",
        "You can wear the summer a little longer.",
        "Sit where the light is last.",
        "You do not need a reason to stay out five more minutes.",
        "The year is still on your side.",
        "A kind night at the end of a warm day.",
        "You can begin the next bit slowly.",
        "Keep this hour. It is yours.",
        "August, held lightly. That is enough.",
        // September
        "A harvest moon, and the first cool morning.",
        "Let September arrive without a speech.",
        "You can start the term as someone kinder to yourself.",
        "New pencils, old luck. Both are allowed.",
        "You do not have to have a five year plan.",
        "A jumper on the chair is a promise of comfort.",
        "Keep the light on in the kitchen a little longer.",
        "You are allowed to need an early night.",
        "The leaves know how to let go. You can practise.",
        "A soup kind of day is a perfectly good day.",
        "You can be grateful without making a list.",
        "There is luck in a scarf that still smells like last year.",
        "You have not failed if you are tired.",
        "Let the dark come in slowly. You can meet it.",
        "A candle is a tiny sun. That will do.",
        "You are allowed to stay in.",
        "The first apple is a ceremony if you let it be.",
        "You can walk home the long way for no reason.",
        "A cooler morning is a clean page.",
        "Keep the people who knock gently.",
        "You can begin again after tea. Many people do.",
        "The year is gathering itself. So can you.",
        "A pocket full of ordinary days, and still you are all right.",
        "You are allowed to want the lights on.",
        "School shoes, new notebooks, old you. All welcome.",
        "Let the evening draw in. You can draw in too.",
        "You do not have to like every hour to like your life.",
        "A warm room waiting is an achievement.",
        "Keep one lovely plan that costs almost nothing.",
        "September will hold you if you let it.",
        // October
        "The beautiful dark, worn lightly.",
        "Keep your humour. October likes it.",
        "You can be a little bit magic and still do the washing up.",
        "A story at night is a kind of blanket.",
        "Let the rain be company, not a mood.",
        "You are safe enough to take the costume off.",
        "A warm room is an achievement. Stay in it.",
        "You can like the dark without fearing it.",
        "Leaves underfoot are a kind of applause.",
        "You are allowed to want soup twice.",
        "The year is getting quieter. That can be a relief.",
        "A wool coat is a kind of armour, and that is fine.",
        "You can ask for the kind version of events.",
        "Hold the ones you love a second longer.",
        "A foggy morning is not a bad omen. It is weather.",
        "Keep the lamp on. It is doing honest work.",
        "You do not have to sparkle. You can just be here.",
        "Let the kettle be the most important meeting.",
        "You are allowed to leave the gathering early.",
        "A photograph of a good day still works.",
        "The dark is only the other half of the light.",
        "You can come home to yourself in a hallway.",
        "A small treat after a long day is not a failure of character.",
        "Keep your softness through the thinner light.",
        "You have not run out of beginnings.",
        "Let this afternoon be a small harbour.",
        "You can wear the lucky thing under the coat.",
        "October will not ask you to be sunny.",
        "A low sky, a high hope, a hot drink.",
        "You are allowed to be a homebody and still be brave.",
        "The month is a dark chocolate, not a test.",
        // November
        "What remains after the fire. Still warm.",
        "November is for soup, socks, and second chances.",
        "You can be low and still be loved.",
        "Let the afternoon lamps come on early.",
        "You do not have to like the weather to like your life.",
        "A thick pair of socks is a policy.",
        "Keep the song that makes the kitchen better.",
        "You can give without emptying yourself.",
        "The year is tired. You are allowed to be too.",
        "A list can wait. A person cannot always.",
        "You are allowed to want less noise.",
        "Let this be a month of early nights and no guilt.",
        "You can find a warm corner and stay there.",
        "A shared umbrella is a kind of luck.",
        "Keep one candle for the ordinary evenings.",
        "You have not used up your luck. It is quieter now, that is all.",
        "The dark comes in. You can meet it with a mug.",
        "You are allowed to skip the extra thing.",
        "A stew on the hob is a love letter to later you.",
        "Let somebody else be impressive this week.",
        "You can be unfinished as the year leans toward its end.",
        "A fogged window, a clear thought.",
        "Keep the people who make winter easier.",
        "You do not have to wait for January to begin again.",
        "A wool blanket and a good page.",
        "You are still here, in the thin light, and that counts.",
        "Let Thursday be as kind as a Sunday.",
        "You can put the heating on and call it self respect.",
        "November will pass. Take the warmth with you.",
        "A quiet pride in having made it this far.",
        // December
        "A small light, kept for the longest night.",
        "You do not have to like December to find a warm corner in it.",
        "Let the year close without a report card.",
        "You are allowed to want next year to be gentler.",
        "A last walk in this year’s weather.",
        "Keep the lucky thought until the morning.",
        "You made it through another year of days. That is not nothing.",
        "Tomorrow can be quiet. You have earned quiet.",
        "The first of the month will come round again, and so will you.",
        "You can put the old year down. It has done its work.",
        "A clean night. A kind mind. That is plenty.",
        "You are still here, and that is the luck we keep.",
        "Go to sleep as if someone kind will wake you.",
        "The next page is blank on purpose.",
        "You do not have to become someone else overnight.",
        "A midnight that asks nothing of you is a gift.",
        "Carry one good sentence into the new year.",
        "You are allowed to hope without a plan.",
        "The charm will still be there in the morning.",
        "Rest now. The light knows the way back.",
        "A year of small lucks is still a lucky year.",
        "You can begin again. You always could.",
        "We are good. You are good. That is the whole note.",
        "Someone is in your corner. Tonight, let it be enough.",
        "The rabbit will be here on the first. Until then, be easy.",
        "A last kind thought, then sleep.",
        "You did not have to do more to deserve this bed.",
        "The year turns. You can turn with it, slowly.",
        "Keep your people. Keep your luck. Keep your softness.",
        "A quiet ending is a beautiful one.",
        "You are held, even on an ordinary night.",
    ]
}
