//
//  Affirmations.swift
//  WhiteRabbits
//
//  One quiet line a day. Secular, light, no homework.
//  Day of the year picks the line, so opening the app is always a small gift.
//  Tone: personal Instagram-positive luck (curated from Reference/affirmations).
//

import Foundation

enum Affirmations {
    static func line(for date: Date = Date()) -> String {
        let day = Calendar.current.ordinality(of: .day, in: .year, for: date) ?? 1
        return all[(day - 1) % all.count]
    }

    /// 365 lines, January to December. A leap day shares 1 March, on purpose.
    static let all: [String] = [
        // January
        "Luck likes you today.",
        "Something lovely is on your side.",
        "Today has a soft spot for you.",
        "Luck is already looking for you.",
        "You're in for a nice surprise.",
        "Things are leaning your way.",
        "You've got good timing today.",
        "Something has your back.",
        "The odds feel friendly to you.",
        "You're exactly where luck can find you.",
        "A bright moment is coming your way.",
        "Today is treating you kindly.",
        "You're due a delightful little win.",
        "Good news suits you.",
        "Something easy is opening up for you.",
        "You're on the lucky side of today.",
        "A happy coincidence has your name on it.",
        "The day is making room for you.",
        "You're closer to something lovely than you think.",
        "A small joy is waiting for you.",
        "Today wants to surprise you nicely.",
        "You've landed in a good moment.",
        "Something is about to go your way.",
        "You're catching life at a lovely angle.",
        "A bit of magic is tucked into your day.",
        "Your next step looks fortunate.",
        "The right thing may find you first.",
        "You've got a little extra luck today.",
        "Something good is already in motion for you.",
        "Today is quietly cheering you on.",
        "You're in the path of something wonderful.",
        // February
        "A lovely answer is heading towards you.",
        "You make good fortune look natural.",
        "Your day has a happy glint to it.",
        "A pleasant twist is coming your way.",
        "You're allowed to expect something nice.",
        "Your timing is better than it seems.",
        "Something sweet is lining up for you.",
        "You're about to feel very glad.",
        "Today is holding a treat for you.",
        "Your luck is warming up.",
        "A tiny triumph is yours today.",
        "You're on the right side of chance.",
        "Something lovely may happen for no reason at all.",
        "Your day is full of friendly possibilities.",
        "You've got a good feeling coming.",
        "Today fits you beautifully.",
        "A lucky break is looking for you.",
        "You're nearer to yes than no.",
        "Something will make you smile today.",
        "Your path looks pleasantly clear.",
        "You have a knack for meeting good moments.",
        "Today comes with a little bonus for you.",
        "You're being met with kindness.",
        "A happy detail will find its way to you.",
        "Your next surprise could be a good one.",
        "You're carrying a little luck with you.",
        "Something is falling neatly into place for you.",
        "Today may be easier than you expected.",
        // March
        "You're in excellent company with chance.",
        "A kind turn is waiting ahead for you.",
        "You're about to catch a lovely moment.",
        "Good things notice you.",
        "Today is saving you a smile.",
        "Your luck has impeccable timing.",
        "A welcome yes is getting closer to you.",
        "You're surrounded by small reasons to feel lucky.",
        "Something bright is choosing your direction.",
        "Your day has promise written all over it.",
        "You're catching a break at just the right time.",
        "A cheerful coincidence is on its way to you.",
        "Today has something special in mind for you.",
        "You're more fortunate than the moment suggests.",
        "A door may open easily for you.",
        "Your good news could arrive quietly.",
        "You're in the right place for a little wonder.",
        "Something kind is unfolding around you.",
        "Today is giving you the benefit of the doubt.",
        "Your next moment might be the lovely one.",
        "You've got a lucky streak in miniature.",
        "A simple pleasure is coming straight to you.",
        "Things are looking up for you.",
        "Today is happy to have you here.",
        "Your world feels a little softer today.",
        "You're about to be pleasantly proved right.",
        "A good chance is drifting your way.",
        "Your day is ready to delight you.",
        "You've got a lovely advantage today.",
        "Something reassuring is finding you.",
        "Today brings you a quiet win.",
        // April
        "Your luck is closer than usual.",
        "You're heading towards a happy little moment.",
        "A thoughtful surprise may reach you today.",
        "The day is taking your side.",
        "Your next turn looks bright.",
        "You're due some effortless joy.",
        "Something good knows where to find you.",
        "Today is giving you a gentle nod.",
        "Your hopes have friendly company.",
        "You've arrived at a promising point.",
        "A lucky detail will stand out to you.",
        "The right moment is making its way to you.",
        "Your day has a little sparkle saved up.",
        "You're in for something unexpectedly sweet.",
        "Good timing is working in your favour.",
        "Today may hand you exactly what you need.",
        "Your corner of the world looks lucky.",
        "You're about to notice something wonderful.",
        "A warm surprise is waiting nearby for you.",
        "The day feels generous towards you.",
        "Your next yes may come easily.",
        "You've got a happy turn ahead.",
        "Something lovely is taking shape for you.",
        "Today is quietly going your way.",
        "You're well placed for good news.",
        "A small delight is about to choose you.",
        "The day is opening kindly for you.",
        "Your timing deserves a little trust.",
        "You've got something nice to look forward to.",
        "A fortunate moment is already on its way.",
        // May
        "Today brings you a reason to grin.",
        "Your path is dotted with pleasant surprises.",
        "You're about to meet a kinder outcome.",
        "Something cheerful is headed your way.",
        "Your next chapter starts with a smile.",
        "You've caught the attention of good fortune.",
        "A welcome change is coming closer to you.",
        "Today is putting in a good word for you.",
        "Your plans may work out beautifully.",
        "You're allowed a day that simply goes well.",
        "Something lovely is waiting around the corner for you.",
        "The little things are lining up in your favour.",
        "Your day has excellent potential.",
        "A lucky thought may lead you somewhere lovely.",
        "Today is offering you a fresh little joy.",
        "Your next coincidence could be a charming one.",
        "You're moving into a gentler stretch.",
        "Something good is making space for you.",
        "The day is full of tiny openings for you.",
        "Your luck is feeling quietly confident.",
        "You're about to receive a lovely reminder.",
        "A bright possibility has noticed you.",
        "Today is likely to be kind to you.",
        "You've got a pleasant surprise in your orbit.",
        "Something is clicking into place for you.",
        "The day is bringing you a small favour.",
        "Your good moment is closer than it looks.",
        "You're in tune with today's lucky details.",
        "A little ease is coming your way.",
        "Today has a happy ending tucked inside it.",
        "Your next move may feel wonderfully natural.",
        // June
        "You've got good things gathering around you.",
        "Something timely is about to reach you.",
        "The day has a lovely opening with your name on it.",
        "You're about to find a reason to feel pleased.",
        "A kind coincidence is choosing you.",
        "Today is smoothing a path for you.",
        "You've got just enough luck for something brilliant.",
        "Something welcome is drawing nearer to you.",
        "The day is keeping a bright spot for you.",
        "Your next discovery may make you smile.",
        "You're entering a particularly lovely moment.",
        "A small piece of good fortune is yours.",
        "Today is sending you a friendly sign.",
        "Your plans have landed on a lucky day.",
        "You're closer to a happy answer.",
        "Something pleasant will catch you off guard.",
        "The day is ready to meet you halfway.",
        "Your luck may show up in a simple way.",
        "You've got a lovely little opening ahead.",
        "A good thing is about to feel possible.",
        "Today is placing something nice within your reach.",
        "Your moment is coming with perfect timing.",
        "You're likely to hear something you'll love.",
        "A lucky choice may feel obvious to you.",
        "The day has a soft surprise waiting.",
        "Your next hour holds something bright.",
        "You've got an easy kind of luck today.",
        "Something sweet may arrive right on cue.",
        "Today is favouring your best-case scenario.",
        "Your way forward has a welcoming glow.",
        // July
        "You're about to stumble upon something delightful.",
        "A pleasant answer is looking for you.",
        "Your luck is hiding in plain sight.",
        "You've got a cheerful turn of events ahead.",
        "Something is going to fit beautifully for you.",
        "Today is making your life a touch lighter.",
        "Your next surprise may be exactly right.",
        "You're in the middle of a lucky little shift.",
        "A moment of ease is waiting for you.",
        "The day is dropping a hint in your favour.",
        "Your good fortune may arrive with a smile.",
        "You've got a lovely chance to enjoy today.",
        "Something is about to feel wonderfully simple.",
        "Today has saved a kind moment for you.",
        "Your next step has luck beside it.",
        "You're drawing closer to something worth celebrating.",
        "A welcome opportunity is finding its way to you.",
        "The day is giving you room to shine.",
        "Your luck is showing up in the details.",
        "You've got a bright little possibility ahead.",
        "Something lovely may choose today to begin.",
        "Today is bringing you a reason to feel hopeful.",
        "Your happy accident is nearly here.",
        "You're about to land on something good.",
        "A gentle surprise is making its way towards you.",
        "The day is quietly arranging something nice.",
        "Your chances look especially friendly.",
        "You've got a good turn coming.",
        "Something is working out better for you.",
        "Today is adding a little shine to your plans.",
        "Your next encounter could be wonderfully timed.",
        // August
        "You're in line for a charming surprise.",
        "A simple yes could brighten your day.",
        "The day has good intentions for you.",
        "Your luck is beginning to show.",
        "You've got a little celebration coming.",
        "Something will land just right for you.",
        "Today is giving your hopes a lift.",
        "You're about to spot a lovely opportunity.",
        "The day is bringing something good within reach.",
        "Your next bit of news may be bright.",
        "You've got a reason to trust today.",
        "Something pleasant is about to become clear.",
        "Today is leaving the light on for you.",
        "Your luck is quietly doing its thing.",
        "You're heading into an easier moment.",
        "A cheerful answer is coming your way.",
        "Your plans are finding their rhythm.",
        "You've got a happy possibility close by.",
        "Something kind may arrive sooner than expected.",
        "Today is holding a place for your joy.",
        "Your next moment comes with a little luck.",
        "You're likely to find what you hoped for.",
        "A bright turn is waiting just ahead.",
        "The day is looking out for you.",
        "Your luck may come disguised as perfect timing.",
        "You've got a wonderful little chance today.",
        "Something is settling in your favour.",
        "Today is ready to be good to you.",
        "Your next hello could lead somewhere lovely.",
        "You're about to enjoy a well-timed surprise.",
        "A small stroke of luck is heading your way.",
        // September
        "The day has a kind answer for you.",
        "Your hopes are closer to home than you think.",
        "You've got a pleasant shift in your future.",
        "Something bright may begin with you today.",
        "Today is making things a touch easier for you.",
        "You're about to receive a little boost.",
        "A lovely possibility is waiting for your attention.",
        "The day is keeping an eye out for you.",
        "Your next choice has a lucky feel to it.",
        "You've got a beautiful bit of timing ahead.",
        "Something good may arrive ahead of schedule.",
        "Today is giving you a reason to feel light.",
        "Your path is crossing with something lovely.",
        "You're due a moment that feels just right.",
        "A warm piece of news may find you.",
        "The day is setting you up for a smile.",
        "Your luck is making a quiet entrance.",
        "You've got an unexpectedly lovely moment ahead.",
        "Something is turning gently in your favour.",
        "Today is bringing a little sweetness your way.",
        "Your next pause may hold a pleasant surprise.",
        "You're moving towards a welcome change.",
        "A friendly chance is waiting for you.",
        "The day is about to brighten around you.",
        "Your good timing may impress you.",
        "You've got a tiny piece of wonderful coming.",
        "Something easy is choosing to stay easy for you.",
        "Today is giving you a lucky nudge.",
        "Your next answer may be the one you wanted.",
        "You're catching the beginning of something good.",
        // October
        "A lovely detail is about to reveal itself to you.",
        "The day has placed a little joy in your path.",
        "You've got a soft landing ahead.",
        "Something bright is waiting to meet you.",
        "Today is warming to your plans.",
        "Your next bit of luck may feel beautifully ordinary.",
        "You're about to find things flowing your way.",
        "A kind opportunity is getting closer.",
        "The day is carrying good news towards you.",
        "Your luck looks lovely from here.",
        "You've got a happy little moment on the horizon.",
        "Something is arriving at exactly the right time.",
        "Your next surprise has good energy.",
        "You're standing near a lucky turn.",
        "A welcome moment is about to unfold for you.",
        "The day is giving you something to smile about.",
        "Your plans are in friendly hands.",
        "You've got a light-hearted win coming.",
        "Today is gently tipping the balance your way.",
        "Your next idea may be a lucky one.",
        "You're about to catch a break that feels deserved.",
        "A happy little extra is waiting for you.",
        "The day is bringing out your fortunate side.",
        "Your luck may surprise you with its simplicity.",
        "You've got a lovely answer on the way.",
        "Something is beginning to bloom for you.",
        "Today is offering you a quiet advantage.",
        "Your next connection could be beautifully timed.",
        "A pleasant turn is coming into view.",
        "The day is making something easier for you.",
        "Your luck is leaving friendly clues.",
        // November
        "You've got a bright reason to keep smiling.",
        "Something lovely may appear out of the blue.",
        "Today is giving your plans a gentle lift.",
        "Your next moment could feel wonderfully lucky.",
        "You're about to get a welcome little sign.",
        "A good thing is moving in your direction.",
        "The day is adding a kind twist to your story.",
        "Your luck has a nice sense of timing.",
        "You've got a sweet surprise waiting in the wings.",
        "Something may work in your favour without fuss.",
        "Today is opening the right window for you.",
        "Your next win may be small and perfect.",
        "You're entering a bright patch.",
        "A lucky detail is about to make sense to you.",
        "The day is bringing you closer to a yes.",
        "Your hopes have a little momentum now.",
        "You've got a charming coincidence ahead.",
        "Something lovely is about to feel real.",
        "Today is giving you the kinder outcome.",
        "Your next step is meeting good timing.",
        "You're about to be glad you were here.",
        "A quiet bit of luck is coming through for you.",
        "The day is making room for a pleasant surprise.",
        "Your good moment may already have begun.",
        "You've got something easy to smile about today.",
        "Something fortunate is falling into your lap.",
        "Today is placing you near a lovely possibility.",
        "Your next bit of joy may arrive unannounced.",
        "You're on the bright side of this moment.",
        "A friendly surprise is on its way.",
        // December
        "The day is choosing a gentle route for you.",
        "Your luck may be closer than your next step.",
        "You've got a beautiful little break ahead.",
        "Something you hoped for may find you today.",
        "Today is wrapping a good moment around you.",
        "Your next coincidence could feel made for you.",
        "You're about to meet a lovely turn of events.",
        "A little more ease is coming to you.",
        "The day is saving its best detail for you.",
        "Your luck has been quietly gathering.",
        "You've got something wonderful drawing near.",
        "A happy ending is still available to you today.",
        "You and good fortune make a lovely pair.",
        "A little nod from the day.",
        "Luck is on your side.",
        "A perfect moment is coming.",
        "You are right on time.",
        "The timing is perfect.",
        "Breathe easy today.",
        "Something good is brewing.",
        "A lucky break is due.",
        "You are in the right place.",
        "A gentle day ahead.",
        "Expect a lovely surprise.",
        "You deserve this good luck.",
        "Things are looking up.",
        "It is all going to click.",
        "The wind is at your back.",
        "Everything is lining up.",
        "You are doing beautifully.",
        "Good things are arriving.",
    ]
}
