//
//  Affirmations.swift
//  WhiteRabbits
//
//  One quiet line a day. Secular, light, no homework.
//  A continuous day-counter picks the line (days since a fixed epoch, mod
//  the bank size), so the whole 500-line bank rotates through over time
//  instead of resetting every January 1st.
//  Tone: personal Instagram-positive luck (curated from Reference/affirmations).
//

import Foundation

enum Affirmations {
    private static let epoch: Date = {
        var components = DateComponents()
        components.year = 2025
        components.month = 1
        components.day = 1
        return Calendar.current.date(from: components) ?? Date(timeIntervalSince1970: 0)
    }()

    static func line(for date: Date = Date()) -> String {
        let calendar = Calendar.current
        let startOfDay = calendar.startOfDay(for: date)
        let startOfEpoch = calendar.startOfDay(for: epoch)
        let daysSinceEpoch = calendar.dateComponents([.day], from: startOfEpoch, to: startOfDay).day ?? 0
        let index = ((daysSinceEpoch % all.count) + all.count) % all.count
        return all[index]
    }

    /// 500 lines, curated. See Reference/affirmations/curation-notes.md for provenance.
    static let all: [String] = [
        "Luck likes you today.",
        "Something lovely is on your side.",
        "Today has a soft spot for you.",
        "Luck is already looking for you.",
        "You're in for a nice surprise.",
        "Things are leaning your way.",
        "You've got good timing today.",
        "Something has your back.",
        "The odds feel friendly to you.",
        "You're exactly where luck can find you.",
        "A bright moment is coming your way.",
        "Today is treating you kindly.",
        "You're due a delightful little win.",
        "Good news suits you.",
        "Something easy is opening up for you.",
        "You're on the lucky side of today.",
        "A happy coincidence has your name on it.",
        "The day is making room for you.",
        "You're closer to something lovely than you think.",
        "A small joy is waiting for you.",
        "Today wants to surprise you nicely.",
        "You've landed in a good moment.",
        "Something is about to go your way.",
        "You're catching life at a lovely angle.",
        "A bit of magic is tucked into your day.",
        "Your next step looks fortunate.",
        "The right thing may find you first.",
        "You've got a little extra luck today.",
        "Something good is already in motion for you.",
        "Today is quietly cheering you on.",
        "You're in the path of something wonderful.",
        "A lovely answer is heading towards you.",
        "Your day has a happy glint to it.",
        "A pleasant twist is coming your way.",
        "You're allowed to expect something nice.",
        "Your timing is better than it seems.",
        "Something sweet is lining up for you.",
        "You're about to feel very glad.",
        "Today is holding a treat for you.",
        "Your luck is warming up.",
        "A tiny triumph is yours today.",
        "You're on the right side of chance.",
        "Something lovely may happen for no reason at all.",
        "Your day is full of friendly possibilities.",
        "You've got a good feeling coming.",
        "A lucky break is looking for you.",
        "You're nearer to yes than no.",
        "Something will make you smile today.",
        "Your path looks pleasantly clear.",
        "You have a knack for meeting good moments.",
        "Today comes with a little bonus for you.",
        "You're being met with kindness.",
        "A happy detail will find its way to you.",
        "Your next surprise could be a good one.",
        "You're carrying a little luck with you.",
        "Something is falling neatly into place for you.",
        "Today may be easier than you expected.",
        "A kind turn is waiting ahead for you.",
        "You're about to catch a lovely moment.",
        "Good things notice you.",
        "Today is saving you a smile.",
        "A welcome yes is getting closer to you.",
        "You're surrounded by small reasons to feel lucky.",
        "Something bright is choosing your direction.",
        "Your day has promise written all over it.",
        "You're catching a break at just the right time.",
        "A cheerful coincidence is on its way to you.",
        "Today has something special in mind for you.",
        "You're more fortunate than the moment suggests.",
        "A door may open easily for you.",
        "Your good news could arrive quietly.",
        "You're in the right place for a little wonder.",
        "Something kind is unfolding around you.",
        "Today is giving you the benefit of the doubt.",
        "Your next moment might be the lovely one.",
        "You've got a lucky streak in miniature.",
        "A simple pleasure is coming straight to you.",
        "Things are looking up for you.",
        "Today is happy to have you here.",
        "Your world feels a little softer today.",
        "A good chance is drifting your way.",
        "Your day is ready to delight you.",
        "You've got a lovely advantage today.",
        "Something reassuring is finding you.",
        "Today brings you a quiet win.",
        "Your luck is closer than usual.",
        "You're heading towards a happy little moment.",
        "A thoughtful surprise may reach you today.",
        "The day is taking your side.",
        "Your next turn looks bright.",
        "You're due some effortless joy.",
        "Something good knows where to find you.",
        "Today is giving you a gentle nod.",
        "You've arrived at a promising point.",
        "A lucky detail will stand out to you.",
        "The right moment is making its way to you.",
        "Your day has a little sparkle saved up.",
        "You're in for something unexpectedly sweet.",
        "Good timing is working in your favour.",
        "Today may hand you exactly what you need.",
        "Your corner of the world looks lucky.",
        "You're about to notice something wonderful.",
        "A warm surprise is waiting nearby for you.",
        "The day feels generous towards you.",
        "Your next yes may come easily.",
        "You've got a happy turn ahead.",
        "Something lovely is taking shape for you.",
        "Today is quietly going your way.",
        "You're well placed for good news.",
        "A small delight is about to choose you.",
        "The day is opening kindly for you.",
        "Your timing deserves a little trust.",
        "You've got something nice to look forward to.",
        "A fortunate moment is already on its way.",
        "Today brings you a reason to grin.",
        "Your path is dotted with pleasant surprises.",
        "You're about to meet a kinder outcome.",
        "Something cheerful is headed your way.",
        "Your next chapter starts with a smile.",
        "A welcome change is coming closer to you.",
        "Your plans may work out beautifully.",
        "You're allowed a day that simply goes well.",
        "Something lovely is waiting around the corner for you.",
        "The little things are lining up in your favour.",
        "Your day has excellent potential.",
        "A lucky thought may lead you somewhere lovely.",
        "Today is offering you a fresh little joy.",
        "Your next coincidence could be a charming one.",
        "You're moving into a gentler stretch.",
        "Something good is making space for you.",
        "The day is full of tiny openings for you.",
        "Your luck is feeling quietly confident.",
        "You're about to receive a lovely reminder.",
        "A bright possibility has noticed you.",
        "Today is likely to be kind to you.",
        "You've got a pleasant surprise in your orbit.",
        "Something is clicking into place for you.",
        "The day is bringing you a small favour.",
        "Your good moment is closer than it looks.",
        "You're in tune with today's lucky details.",
        "A little ease is coming your way.",
        "Today has a happy ending tucked inside it.",
        "Your next move may feel wonderfully natural.",
        "You've got good things gathering around you.",
        "Something timely is about to reach you.",
        "The day has a lovely opening with your name on it.",
        "You're about to find a reason to feel pleased.",
        "A kind coincidence is choosing you.",
        "Today is smoothing a path for you.",
        "Something welcome is drawing nearer to you.",
        "The day is keeping a bright spot for you.",
        "Your next discovery may make you smile.",
        "You're entering a particularly lovely moment.",
        "A small piece of good fortune is yours.",
        "Today is sending you a friendly sign.",
        "Your plans have landed on a lucky day.",
        "You're closer to a happy answer.",
        "Something pleasant will catch you off guard.",
        "The day is ready to meet you halfway.",
        "Your luck may show up in a simple way.",
        "You've got a lovely little opening ahead.",
        "A good thing is about to feel possible.",
        "Today is placing something nice within your reach.",
        "You're likely to hear something you'll love.",
        "A lucky choice may feel obvious to you.",
        "The day has a soft surprise waiting.",
        "Your next hour holds something bright.",
        "You've got an easy kind of luck today.",
        "Something sweet may arrive right on cue.",
        "Your way forward has a welcoming glow.",
        "You're about to stumble upon something delightful.",
        "A pleasant answer is looking for you.",
        "Your luck is hiding in plain sight.",
        "You've got a cheerful turn of events ahead.",
        "Something is going to fit beautifully for you.",
        "Today is making your life a touch lighter.",
        "Your next surprise may be exactly right.",
        "You're in the middle of a lucky little shift.",
        "A moment of ease is waiting for you.",
        "The day is dropping a hint in your favour.",
        "Your good fortune may arrive with a smile.",
        "You've got a lovely chance to enjoy today.",
        "Something is about to feel wonderfully simple.",
        "Today has saved a kind moment for you.",
        "Your next step has luck beside it.",
        "You're drawing closer to something worth celebrating.",
        "A welcome opportunity is finding its way to you.",
        "The day is giving you room to shine.",
        "Your luck is showing up in the details.",
        "You've got a bright little possibility ahead.",
        "Something lovely may choose today to begin.",
        "Today is bringing you a reason to feel hopeful.",
        "Your happy accident is nearly here.",
        "You're about to land on something good.",
        "A gentle surprise is making its way towards you.",
        "The day is quietly arranging something nice.",
        "Your chances look especially friendly.",
        "You've got a good turn coming.",
        "Something is working out better for you.",
        "Today is adding a little shine to your plans.",
        "Your next encounter could be wonderfully timed.",
        "You're in line for a charming surprise.",
        "A simple yes could brighten your day.",
        "Your luck is beginning to show.",
        "You've got a little celebration coming.",
        "Something will land just right for you.",
        "Today is giving your hopes a lift.",
        "You're about to spot a lovely opportunity.",
        "The day is bringing something good within reach.",
        "Your next bit of news may be bright.",
        "You've got a reason to trust today.",
        "Something pleasant is about to become clear.",
        "Today is leaving the light on for you.",
        "Your luck is quietly doing its thing.",
        "You're heading into an easier moment.",
        "A cheerful answer is coming your way.",
        "Your plans are finding their rhythm.",
        "You've got a happy possibility close by.",
        "Something kind may arrive sooner than expected.",
        "Today is holding a place for your joy.",
        "Your next moment comes with a little luck.",
        "You're likely to find what you hoped for.",
        "A bright turn is waiting just ahead.",
        "The day is looking out for you.",
        "Your luck may come disguised as perfect timing.",
        "You've got a wonderful little chance today.",
        "Something is settling in your favour.",
        "Today is ready to be good to you.",
        "Your next hello could lead somewhere lovely.",
        "You're about to enjoy a well-timed surprise.",
        "A small stroke of luck is heading your way.",
        "The day has a kind answer for you.",
        "You've got a pleasant shift in your future.",
        "Something bright may begin with you today.",
        "Today is making things a touch easier for you.",
        "You're about to receive a little boost.",
        "A lovely possibility is waiting for your attention.",
        "Your next choice has a lucky feel to it.",
        "You've got a beautiful bit of timing ahead.",
        "Something good may arrive ahead of schedule.",
        "Today is giving you a reason to feel light.",
        "Your path is crossing with something lovely.",
        "You're due a moment that feels just right.",
        "A warm piece of news may find you.",
        "The day is setting you up for a smile.",
        "Your luck is making a quiet entrance.",
        "You've got an unexpectedly lovely moment ahead.",
        "Something is turning gently in your favour.",
        "Today is bringing a little sweetness your way.",
        "Your next pause may hold a pleasant surprise.",
        "You're moving towards a welcome change.",
        "A friendly chance is waiting for you.",
        "The day is about to brighten around you.",
        "You've got a tiny piece of wonderful coming.",
        "Something easy is choosing to stay easy for you.",
        "Today is giving you a lucky nudge.",
        "Your next answer may be the one you wanted.",
        "You're catching the beginning of something good.",
        "A lovely detail is about to reveal itself to you.",
        "The day has placed a little joy in your path.",
        "You've got a soft landing ahead.",
        "Something bright is waiting to meet you.",
        "Your next bit of luck may feel beautifully ordinary.",
        "You're about to find things flowing your way.",
        "A kind opportunity is getting closer.",
        "The day is carrying good news towards you.",
        "You've got a happy little moment on the horizon.",
        "Something is arriving at exactly the right time.",
        "You're standing near a lucky turn.",
        "A welcome moment is about to unfold for you.",
        "The day is giving you something to smile about.",
        "You've got a light-hearted win coming.",
        "Today is gently tipping the balance your way.",
        "Your next idea may be a lucky one.",
        "You're about to catch a break that feels deserved.",
        "A happy little extra is waiting for you.",
        "Your luck may surprise you with its simplicity.",
        "You've got a lovely answer on the way.",
        "Something is beginning to bloom for you.",
        "Today is offering you a quiet advantage.",
        "Your next connection could be beautifully timed.",
        "A pleasant turn is coming into view.",
        "The day is making something easier for you.",
        "You've got a bright reason to keep smiling.",
        "Something lovely may appear out of the blue.",
        "Today is giving your plans a gentle lift.",
        "Your next moment could feel wonderfully lucky.",
        "You're about to get a welcome little sign.",
        "A good thing is moving in your direction.",
        "The day is adding a kind twist to your story.",
        "You've got a sweet surprise waiting in the wings.",
        "Something may work in your favour without fuss.",
        "Today is opening the right window for you.",
        "Your next win may be small and perfect.",
        "You're entering a bright patch.",
        "A lucky detail is about to make sense to you.",
        "The day is bringing you closer to a yes.",
        "Your hopes have a little momentum now.",
        "You've got a charming coincidence ahead.",
        "Something lovely is about to feel real.",
        "Today is giving you the kinder outcome.",
        "Your next step is meeting good timing.",
        "You're about to be glad you were here.",
        "A quiet bit of luck is coming through for you.",
        "The day is making room for a pleasant surprise.",
        "Your good moment may already have begun.",
        "You've got something easy to smile about today.",
        "Something fortunate is falling into your lap.",
        "Today is placing you near a lovely possibility.",
        "Your next bit of joy may arrive unannounced.",
        "You're on the bright side of this moment.",
        "A friendly surprise is on its way.",
        "You've got a beautiful little break ahead.",
        "Something you hoped for may find you today.",
        "You're about to meet a lovely turn of events.",
        "A little more ease is coming to you.",
        "You've got something wonderful drawing near.",
        "A little nod from the day.",
        "Luck is on your side.",
        "You are right on time.",
        "The timing is perfect.",
        "Breathe easy today.",
        "Something good is brewing.",
        "A lucky break is due.",
        "You are in the right place.",
        "A gentle day ahead.",
        "Expect a lovely surprise.",
        "You deserve this good luck.",
        "Things are looking up.",
        "The wind is at your back.",
        "You are doing beautifully.",
        "Good things are arriving.",
        "There is room for something lovely today.",
        "A small good thing can still surprise you.",
        "Let today be kinder than expected.",
        "You may notice luck in an ordinary place.",
        "A little brightness belongs in your day.",
        "There is something nice about this moment already.",
        "Today can unfold without needing to be perfect.",
        "A gentle bit of luck may find you.",
        "Keep an eye out for the small good stuff.",
        "You are allowed to enjoy an easy moment.",
        "A tiny win still counts as a win.",
        "There is plenty of day left for something good.",
        "A kind moment can change the feel of a day.",
        "Something simple may make you very happy.",
        "You may be closer to ease than you think.",
        "Today has space for a pleasant surprise.",
        "A little luck can arrive quietly.",
        "Good moments do not need to be dramatic.",
        "You might find exactly the right thing at the right time.",
        "There is a soft little win waiting somewhere in today.",
        "Let the nice bit count.",
        "A small coincidence may make you smile.",
        "Today may have a kinder rhythm.",
        "A good moment can begin very simply.",
        "There is luck in noticing what is already lovely.",
        "One bright thing is enough to shift the day.",
        "You do not have to chase every good thing.",
        "Some nice things arrive on their own.",
        "Today may surprise you in a small way.",
        "A little ease can go a long way.",
        "You can leave room for something good.",
        "The day does not have to be complicated to be lovely.",
        "A small kindness may land exactly when you need it.",
        "There is time for the day to turn sweet.",
        "You may stumble into a moment worth keeping.",
        "Something ordinary may feel especially nice today.",
        "A quiet win can still feel wonderful.",
        "Let today bring its own little charm.",
        "You may get a reason to smile for no big reason.",
        "A good moment may be closer than it looks.",
        "There is a bit of luck in taking things as they come.",
        "Today can be gentle with you.",
        "A lovely little detail may stand out.",
        "You may find the easy answer.",
        "A warm moment could arrive unexpectedly.",
        "There is room for a lucky turn.",
        "A small yes can be enough.",
        "You may notice that something feels lighter.",
        "Today can hold more than one good thing.",
        "The right little thing may show up at the right time.",
        "A pleasant surprise does not need an announcement.",
        "You can let a good moment be just that.",
        "Something may work out with less fuss than expected.",
        "There is a kind corner of today waiting for you.",
        "A little good news would suit you nicely.",
        "You may be pleasantly surprised by how simple something feels.",
        "Today has room for a cheerful detour.",
        "A small stroke of luck can change the mood.",
        "You can trust a nice moment when it arrives.",
        "There is a little brightness on the way through.",
        "Something may click without forcing it.",
        "A good thing can begin quietly.",
        "You may find yourself in the right place by accident.",
        "Today can offer a softer landing.",
        "A tiny bit of luck is still luck.",
        "There is nothing wrong with hoping for a nice surprise.",
        "You may get one of those oddly perfect little moments.",
        "A kind answer may come easily.",
        "Today might feel lighter around the edges.",
        "You can enjoy the part that goes well.",
        "A small piece of ease may find you.",
        "There is room for delight in an ordinary day.",
        "You may notice something worth being glad about.",
        "A good turn can happen without warning.",
        "Today may hand you a lovely little extra.",
        "You can keep the nice moment.",
        "Something simple may go exactly right.",
        "There is a friendly possibility in the air.",
        "You may catch a break in a very ordinary way.",
        "A bit of good timing could help.",
        "Today can contain a tiny bit of magic without making a fuss.",
        "You may find a reason to feel lucky.",
        "A soft surprise could be enough.",
        "There is still room for the day to charm you.",
        "You can let something be easier than expected.",
        "A good moment may sneak up on you.",
        "Today may bring a little lift.",
        "You may hear exactly what you needed to hear.",
        "A small pleasure can be the best part.",
        "There is luck in the little things too.",
        "You may find the right words at the right moment.",
        "Today can give you a quiet reason to grin.",
        "A gentle yes may be on its way.",
        "You can notice what feels good without overthinking it.",
        "Something lovely may happen in passing.",
        "There is a chance for today to feel easy.",
        "You may get a nice surprise from an ordinary place.",
        "A tiny happy accident could be enough.",
        "Today can bring a little more ease.",
        "You may find something that fits just right.",
        "A kind moment can arrive from nowhere.",
        "There is room for a lucky little coincidence.",
        "You may get the timing you hoped for.",
        "Today can be nicer than it first appears.",
        "A small bright thing may catch your attention.",
        "You can take the win, however small.",
        "Something may go your way without needing a reason.",
        "There is a little luck in being here now.",
        "You may be glad you took the next step.",
        "Today may offer one beautifully simple thing.",
        "A quiet bit of good fortune may pass your way.",
        "You can let the day surprise you.",
        "Something may feel easier once you get there.",
        "There is room for good news in a normal day.",
        "You may find yourself smiling before you know why.",
        "A small change could feel very welcome.",
        "Today can still turn out sweet.",
        "You may get a lovely little break.",
        "A kind coincidence could make the day.",
        "There is something to be said for good timing.",
        "You may find the thing you nearly gave up looking for.",
        "Today can hold a welcome bit of luck.",
        "A small moment may feel unexpectedly special.",
        "You can leave space for a nice outcome.",
        "Something good may be hiding in the ordinary.",
        "There is room for the right thing to happen quietly.",
        "You may get a simple reason to feel hopeful.",
        "Today could contain a very well-timed yes.",
        "A little luck can look like less hassle.",
        "You can enjoy the easy bit when it comes.",
        "Something may land more gently than expected.",
        "There is a lovely possibility somewhere in today.",
        "You may get a bright little reminder that things can go well.",
        "Today can be generous in a small way.",
        "A quiet surprise could be exactly enough.",
        "You can let a pleasant moment interrupt you.",
        "Something may fall into place without fanfare.",
        "There is room for a friendly turn of events.",
        "You may find that the timing works after all.",
        "Today could offer a little unexpected ease.",
        "A small win may arrive disguised as convenience.",
        "You can count the good bit.",
        "Something simple may brighten the whole afternoon.",
        "There is a tiny bit of luck with your name on it.",
        "You may catch one of those days when things just flow.",
        "Today can still hand you something lovely.",
        "A warm little moment may find you first.",
        "You can let good timing do some of the work.",
        "Something may feel surprisingly straightforward.",
        "There is room for the day to be on your side.",
        "You may spot a chance you did not see before.",
        "Today could bring one very satisfying little win.",
        "A small piece of good news may travel your way.",
        "You can be open to the nice surprise.",
        "Something kind may happen at exactly the right moment.",
        "There is a good chance of a good moment.",
        "You may find that one thing goes more smoothly than expected.",
        "Today can have a lucky edge to it.",
        "A quiet yes can still mean a lot.",
        "You can take the pleasant surprise without questioning it.",
        "Something may turn out better than it looked at first.",
        "There is room for one lovely little thing after another.",
        "You may notice the day softening around you.",
        "Today could give you a reason to say, “Well, that was nice.”",
        "A small bit of luck may arrive right on cue.",
        "You can let today be simple and good.",
        "Something lovely may already be beginning.",
        "A little good fortune may be closer than you think.",
    ]
}
